theme: minima
title: Abdul Moiz Asif Life
author: Moiz
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Life is full of moments of joy, pleasure, success and comfort punctuated by misery, defeat, failures and problems. 
  There is no human being on Earth, strong, powerful, wise or rich, who has not experienced, struggle, suffering or failure. 
  You have to work hard to reach to the highest position.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
